### PR TITLE
feature: add synapse workspace & synapse spark pool cmd's

### PR DESCRIPTION
**Pull request by vanwinkelseppe**
# Description

Added a scanner for 

- Synapse Analytics Workspaces
- Synapse Spark Pools
- Synapse Dedicated SQL Pools

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #203 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Unit tests passing

### CODE REVIEW

**Comment by vanwinkelseppe** [comment]
@cmendible updated the code to remove the ineffectual assignment to err in the linter.

**Comment by vanwinkelseppe** [comment]
Also added Azure Synapse Dedicated SQL pools

**Review by cmendible — CHANGES_REQUESTED** [review]
**Thanks for your contribution!** 

This implementation potentially scans for workspaces 3 times if a user runs a scan without subcommands.

In order to avoid this:

* Centralize all synapse scans under the  `synw` sub command and remove the other two.
* `synw` scan should run `synw` scan as well as `syndp` so we query for workspaces just once.
* You can check a similar behavior in the `asp` scanner here: https://github.com/Azure/azqr/blob/6f1e35b7403d1ce18ae14ce85a9d1f35bf01ff5d/internal/scanners/asp/asp.go#L44

**Comment by vanwinkelseppe** [comment]
> **Thanks for your contribution!**
> 
> This implementation potentially scans for workspaces 3 times if a user runs a scan without subcommands.
> 
> In order to avoid this:
> 
> * Centralize all synapse scans under the  `synw` sub command and remove the other two.
> * `synw` scan should run `synw` scan as well as `syndp` so we query for workspaces just once.
> * You can check a similar behavior in the `asp` scanner here: https://github.com/Azure/azqr/blob/6f1e35b7403d1ce18ae14ce85a9d1f35bf01ff5d/internal/scanners/asp/asp.go#L44

Thanks! Will do this asap!

**Review by cmendible — APPROVED** [review]
LGTM

**Pull request merged**
